---
- name: Include OS-specific tasks.
  ansible.builtin.include_tasks: "{{ ansible_os_family }}_pre_tasks.yml"

- ansible.builtin.import_tasks: "setup_dotfiles_repo.yml"
- ansible.builtin.import_tasks: "setup_bash.yml"
- ansible.builtin.import_tasks: "setup_xdg_dirs.yml"
- ansible.builtin.import_tasks: "setup_xdg_config_home_programs.yml"
- ansible.builtin.import_tasks: "setup_necessary_dirs.yml"
