---
- name: Make {{ type }} directories.
  ansible.builtin.file:
    path:
      "{{ lookup('ansible.builtin.vars', type + '_dirs')['base'] }}/{{ dir }}"
    state: "directory"
    mode: "0700"
    group: "{{ ansible_facts['user_id'] }}"
    owner: "{{ ansible_facts['user_id'] }}"
  loop: "{{ lookup('ansible.builtin.vars', type + '_dirs')['dirs'] }}"
  loop_control:
    loop_var: "dir"
  become: true
