---
- name: Find configurations in {{ dotfiles_repo_local_destination }}/.config
  ansible.builtin.command:
    "find {{ dotfiles_repo_local_destination }}/.config \
      -mindepth 1 \
      -maxdepth 1 \
      -printf '%f\n' \
    "
  failed_when: false
  check_mode: false
  changed_when: false
  register: configs
  become: false

- name: Ensure all configured dotfiles are links.
  ansible.builtin.command: "ls -F {{ xdg_config_home.stdout }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ configs.stdout_lines }}"
  become: false

- name: Remove existing dotfiles if a replacement is being linked.
  ansible.builtin.file:
    path: "{{ xdg_config_home.stdout }}/{{ item.item }}"
    state: absent
  when: "'@' not in item.stdout"
  become: false
  loop: "{{ existing_dotfile_info.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Link dotfiles into {{ xdg_config_home.stdout }}.
  ansible.builtin.file:
    src: "{{ dotfiles_repo_local_destination }}/.config/{{ item }}"
    dest: "{{ xdg_config_home.stdout }}/{{ item }}"
    state: link
  become: false
  with_items: "{{ configs.stdout_lines }}"

